# -*- coding: utf-8 -*-
"""
Listado curado de revistas latinoamericanas de educación y ciencias sociales
fuera del Núcleo Básico argentino.

Formato: (nombre, país, institución, sitio_url, indexación_declarada)

`sitio_url` vacío = el enlace original era una búsqueda de Google, no una URL
real. Esas se resuelven contra OpenAlex por nombre (ver externas.py); no se
inventan.

`indexación_declarada` es lo que afirma la fuente del listado. NO se toma como
verdad: externas.py la contrasta contra la lista oficial de Scopus, las
colecciones de SciELO y DOAJ, y la app muestra ambas para poder compararlas.
"""

REVISTAS = [
    # ─────────────────────────── CHILE ───────────────────────────
    ("Psicoperspectivas. Individuo y Sociedad", "Chile", "Pontificia Universidad Católica de Valparaíso",
     "https://www.psicoperspectivas.cl/index.php/psicoperspectivas", "Scopus / WoS / SciELO"),
    ("Perspectiva Educacional", "Chile", "Pontificia Universidad Católica de Valparaíso",
     "https://www.perspectivaeducacional.cl/", "Scopus / SciELO"),
    ("Pensamiento Educativo", "Chile", "Pontificia Universidad Católica de Chile",
     "https://pensamientoeducativo.uc.cl/", "Scopus / SciELO"),
    ("Estudios Pedagógicos", "Chile", "Universidad Austral de Chile", "", "Scopus / SciELO"),
    ("Calidad en la Educación", "Chile", "Consejo Nacional de Educación", "", "Scopus / SciELO"),
    ("Revista de Estudios y Experiencias en Educación", "Chile",
     "Universidad Católica de la Santísima Concepción",
     "https://rexe.cl/index.php/rexe", "SciELO / Latindex / Redalyc"),
    ("Revista Enfoques Educacionales", "Chile", "Universidad de Chile",
     "https://enfoqueseducacionales.uchile.cl/", "Latindex Catálogo / ERIH PLUS"),
    ("Revista de Pedagogía Crítica", "Chile", "Universidad Academia de Humanismo Cristiano",
     "", "no declarada"),
    ("Polis. Revista Latinoamericana", "Chile", "Universidad de Los Lagos (CEDER)",
     "", "Scopus / SciELO / Redalyc"),
    ("Cinta de Moebio", "Chile", "Universidad de Chile",
     "https://cintademoebio.uchile.cl/", "Scopus / SciELO / DOAJ"),
    ("Revista de Sociología", "Chile", "Universidad de Chile",
     "https://revistadesociologia.uchile.cl/", "SciELO / DOAJ / Latindex"),
    ("Persona y Sociedad", "Chile", "Universidad Alberto Hurtado",
     "https://personaysociedad.cl/", "ERIH PLUS / Latindex / DOAJ"),
    ("Izquierdas", "Chile", "Universidad de Santiago de Chile",
     "https://www.izquierdas.cl/", "Scopus / WoS / SciELO"),

    # ─────────────────────────── BRASIL ───────────────────────────
    ("Educação & Sociedade", "Brasil", "CEDES / Unicamp",
     "https://www.scielo.br/j/es/", "Scopus / WoS / SciELO"),
    ("Educação e Realidade", "Brasil", "Universidade Federal do Rio Grande do Sul",
     "https://www.scielo.br/j/edreal/", "Scopus / SciELO / DOAJ"),
    ("Cadernos de Pesquisa", "Brasil", "Fundação Carlos Chagas",
     "https://publicacoes.fcc.org.br/cp", "Scopus / SciELO / Redalyc"),
    ("Revista Brasileira de Educação", "Brasil", "ANPEd",
     "https://www.scielo.br/j/rbedu/", "Scopus / SciELO / Redalyc"),
    ("Educação e Pesquisa", "Brasil", "Faculdade de Educação da USP",
     "https://www.revistas.usp.br/ep", "Scopus / SciELO"),
    ("Ensaio: Avaliação e Políticas Públicas em Educação", "Brasil", "Fundação Cesgranrio",
     "https://revistas.cesgranrio.org.br/index.php/ensaio", "Scopus / WoS / SciELO"),
    ("Práxis Educativa", "Brasil", "Universidade Estadual de Ponta Grossa",
     "https://revistas.uepg.br/index.php/praxiseducativa", "Scopus / SciELO"),
    ("Currículo sem Fronteiras", "Brasil/Portugal", "Edição binacional",
     "https://www.curriculosemfronteiras.org/", "Scopus / Latindex"),
    ("Educação em Revista", "Brasil", "Universidade Federal de Minas Gerais",
     "https://www.scielo.br/j/edur/", "Scopus / SciELO"),
    ("Revista Educação em Questão", "Brasil", "Universidade Federal do Rio Grande do Norte",
     "https://periodicos.ufrn.br/educacaoemquestao", "SciELO / Latindex / Redalyc"),
    ("Acta Scientiarum. Education", "Brasil", "Universidade Estadual de Maringá",
     "https://periodicos.uem.br/ojs/index.php/ActaSciEduc", "Scopus / DOAJ"),
    ("Revista Brasileira de Política e Administração da Educação", "Brasil", "ANPAE",
     "https://seer.ufrgs.br/index.php/rbpae", "Scopus / Latindex / Qualis A1"),
    ("Estudos em Avaliação Educacional", "Brasil", "Fundação Carlos Chagas",
     "https://publicacoes.fcc.org.br/eae", "Scopus / SciELO / DOAJ"),
    ("Pro-Posições", "Brasil", "Faculdade de Educação da Unicamp",
     "https://www.scielo.br/j/pp/", "Scopus / SciELO / WoS"),
    ("Cadernos CEDES", "Brasil", "CEDES / Unicamp",
     "https://www.scielo.br/j/ccedes/", "Scopus / SciELO / WoS"),
    ("Tempo Social", "Brasil", "Universidade de São Paulo", "", "Scopus / WoS / SciELO"),
    ("Novos Estudos CEBRAP", "Brasil", "CEBRAP",
     "https://novosestudos.com.br/", "Scopus / SciELO / DOAJ"),
    ("Dados - Revista de Ciências Sociais", "Brasil", "IESP / UERJ",
     "https://dados.iesp.uerj.br/", "Scopus / WoS / SciELO"),
    ("Sociedade e Estado", "Brasil", "Universidade de Brasília",
     "https://www.scielo.br/j/se/", "Scopus / SciELO / Redalyc"),
    ("Revista Brasileira de Ciências Sociais", "Brasil", "ANPOCS",
     "", "Scopus / SciELO / Redalyc"),
    ("Mana. Estudos de Antropologia Social", "Brasil", "Museu Nacional / UFRJ",
     "https://www.scielo.br/j/mana/", "Scopus / WoS / SciELO"),

    # ─────────────────────────── URUGUAY ───────────────────────────
    ("Cuadernos de Investigación Educativa", "Uruguay", "Universidad ORT Uruguay",
     "https://revistas.ort.edu.uy/cuadernos-de-investigacion-educativa", "Scopus / SciELO / DOAJ"),
    ("Páginas de Educación", "Uruguay", "Universidad Católica del Uruguay",
     "", "SciELO / Latindex / DOAJ"),
    ("Revista Uruguaya de Ciencia Política", "Uruguay",
     "Instituto de Ciencia Política, UdelaR", "", "Scopus / SciELO"),
    ("Revista de Ciencias Sociales (UdelaR)", "Uruguay",
     "Departamento de Sociología, UdelaR", "", "SciELO / Redalyc / Latindex"),
    ("Prisma de Sentido", "Uruguay", "Universidad Católica del Uruguay",
     "", "Latindex Catálogo / DOAJ"),

    # ─────────────────────────── PERÚ ───────────────────────────
    ("Educación (PUCP)", "Perú", "Pontificia Universidad Católica del Perú",
     "https://revistas.pucp.edu.pe/index.php/educacion", "Scopus / SciELO / ERIH PLUS"),
    ("Revista Digital de Investigación en Docencia Universitaria", "Perú",
     "Universidad Peruana de Ciencias Aplicadas",
     "https://revistas.upc.edu.pe/index.php/docencia", "Scopus / SciELO"),
    ("Propósitos y Representaciones", "Perú", "Universidad San Ignacio de Loyola",
     "https://revistas.usil.edu.pe/index.php/pyr", "Scopus / SciELO / DOAJ"),
    ("Comuni@cción", "Perú", "Universidad Nacional del Altiplano de Puno",
     "", "Scopus / SciELO"),
    ("Debates en Sociología", "Perú", "Pontificia Universidad Católica del Perú",
     "", "ERIH PLUS / Latindex Catálogo / DOAJ"),
    ("Anthropologica", "Perú", "Pontificia Universidad Católica del Perú",
     "https://revistas.pucp.edu.pe/index.php/anthropologica", "Scopus / SciELO / Redalyc"),
    ("Investigaciones Sociales", "Perú", "Universidad Nacional Mayor de San Marcos",
     "https://revistasinvestigacion.unmsm.edu.pe/index.php/sociales",
     "Latindex Catálogo / DOAJ"),
    ("Revista de Sociología (UNMSM)", "Perú", "Universidad Nacional Mayor de San Marcos",
     "https://revistasinvestigacion.unmsm.edu.pe/index.php/sociologia", "Latindex"),

    # ─────────────────────────── PARAGUAY ───────────────────────────
    ("Revista Científica Estudios e Investigaciones", "Paraguay", "Universidad Iberoamericana",
     "https://revista.unibe.edu.py/index.php/rcei", "SciELO Paraguay / Latindex / DOAJ"),
    ("Academo", "Paraguay", "Universidad Americana",
     "https://revistacientifica.uamericana.edu.py/index.php/academo",
     "SciELO Paraguay / Redalyc / Latindex"),
    ("Revista Paraguaya de Educación", "Paraguay", "OEI Paraguay / INEE",
     "", "Catálogos OEI / Latindex"),
    ("Revista de la Sociedad Científica del Paraguay", "Paraguay",
     "Sociedad Científica del Paraguay", "", "SciELO Paraguay / Latindex"),
    ("Población y Desarrollo", "Paraguay", "Universidad Nacional de Asunción",
     "", "SciELO Paraguay / DOAJ"),
    ("Revista Paraguaya de Sociología", "Paraguay",
     "Centro Paraguayo de Estudios Sociológicos", "", "Latindex / CLACSO"),
    ("Novapolis", "Paraguay", "FLACSO Paraguay", "", "Latindex Catálogo / CLACSO"),

    # ─────────────────────────── COLOMBIA ───────────────────────────
    ("Revista Colombiana de Educación", "Colombia", "Universidad Pedagógica Nacional",
     "", "Scopus / SciELO / Redalyc"),
    ("Pedagogía y Saberes", "Colombia", "Universidad Pedagógica Nacional",
     "", "SciELO / Redalyc / DOAJ"),
    ("Educación y Educadores", "Colombia", "Universidad de La Sabana",
     "https://educacionyeducadores.unisabana.edu.co/index.php/eye", "Scopus / SciELO / Redalyc"),
    ("Magis. Revista Internacional de Investigación en Educación", "Colombia",
     "Pontificia Universidad Javeriana",
     "https://revistas.javeriana.edu.co/index.php/MAGIS/", "Scopus / SciELO / Redalyc"),
    ("Revista Latinoamericana de Ciencias Sociales, Niñez y Juventud", "Colombia",
     "CINDE / Universidad de Manizales",
     "https://revistaumanizales.cinde.org.co/rlcsnj/index.php/Revista-Latinoamericana",
     "Scopus / SciELO / Redalyc"),
    ("Revista Colombiana de Sociología", "Colombia", "Universidad Nacional de Colombia",
     "https://revistas.unal.edu.co/index.php/recs", "Scopus / SciELO / Redalyc"),
    ("Revista de Estudios Sociales", "Colombia", "Universidad de los Andes",
     "https://revistas.uniandes.edu.co/index.php/res", "Scopus / WoS / SciELO"),
    ("Análisis Político", "Colombia", "IEPRI, Universidad Nacional de Colombia",
     "https://revistas.unal.edu.co/index.php/anpol", "Scopus / SciELO / Redalyc"),
    ("Nómadas", "Colombia", "IESCO, Universidad Central",
     "https://nomadas.ucentral.edu.co/", "Scopus / SciELO / Redalyc"),

    # ─────────────────────────── ECUADOR ───────────────────────────
    ("Alteridad. Revista de Educación", "Ecuador", "Universidad Politécnica Salesiana",
     "https://alteridad.ups.edu.ec/index.php/alteridad", "Scopus / SciELO / Redalyc / WoS"),
    ("Sophia. Colección de Filosofía de la Educación", "Ecuador",
     "Universidad Politécnica Salesiana",
     "https://sophia.ups.edu.ec/index.php/sophia", "Scopus / SciELO / Redalyc"),
    ("Revista Andina de Educación", "Ecuador", "Universidad Andina Simón Bolívar",
     "https://revistas.uasb.edu.ec/index.php/ree", "DOAJ / Latindex / Dialnet"),
    ("Íconos. Revista de Ciencias Sociales", "Ecuador", "FLACSO Ecuador",
     "https://iconos.flacsoandes.edu.ec/index.php/iconos", "Scopus / SciELO / Redalyc / WoS"),
    ("Ecuador Debate", "Ecuador", "Centro Andino de Acción Popular", "", "Latindex / CLACSO"),
    ("Eutopía. Revista de Desarrollo Económico Territorial", "Ecuador", "FLACSO Ecuador",
     "", "Scopus / Latindex / DOAJ"),
    ("URVIO. Revista Latinoamericana de Estudios de Seguridad", "Ecuador", "FLACSO Ecuador",
     "", "Scopus / Latindex / DOAJ"),

    # ─────────────────────────── VENEZUELA ───────────────────────────
    ("Revista de Pedagogía (UCV)", "Venezuela", "Universidad Central de Venezuela",
     "", "Redalyc / Latindex"),
    ("Educere", "Venezuela", "Universidad de los Andes", "", "Redalyc / Latindex / Dialnet"),
    ("Omnia", "Venezuela", "Universidad del Zulia", "", "Redalyc / Latindex"),
    ("Revista de Ciencias Sociales (LUZ)", "Venezuela", "Universidad del Zulia",
     "https://produccioncientificaluz.org/index.php/rcs", "Scopus / Redalyc / SciELO"),
    ("Espacio Abierto", "Venezuela", "Universidad del Zulia", "", "Scopus / Redalyc / Latindex"),
    ("Cuestiones Políticas", "Venezuela", "Universidad del Zulia",
     "https://produccioncientificaluz.org/index.php/cuestiones", "Scopus / WoS / Redalyc"),
    ("Revista Venezolana de Análisis de Coyuntura", "Venezuela",
     "Universidad Central de Venezuela", "", "Latindex / CLACSO"),

    # ─────────────────────────── CUBA ───────────────────────────
    ("Revista Cubana de Educación Superior", "Cuba", "CEPES, Universidad de La Habana",
     "", "SciELO Cuba / DOAJ / Latindex"),
    ("Atenas", "Cuba", "Universidad de Matanzas",
     "https://atenas.umcc.cu/index.php/atenas", "Redalyc / SciELO / DOAJ"),
    ("Mendive. Revista de Educación", "Cuba", "Universidad de Pinar del Río",
     "", "SciELO Cuba / DOAJ / Latindex"),
    ("Varona. Revista Científico-Pedagógica", "Cuba",
     "Universidad de Ciencias Pedagógicas Enrique José Varona",
     "", "Redalyc / SciELO Cuba / Latindex"),
    ("Temas", "Cuba", "Publicación cultural y sociopolítica", "", "CLACSO / Latindex"),
    ("Islas", "Cuba", "Universidad Central Marta Abreu de Las Villas",
     "https://islas.uclv.edu.cu/index.php/islas", "Latindex Catálogo / DOAJ"),
    ("Universidad de La Habana", "Cuba", "Universidad de La Habana",
     "", "SciELO Cuba / Latindex / DOAJ"),

    # ─────────────────────────── COSTA RICA ───────────────────────────
    ("Revista Electrónica Educare", "Costa Rica", "Universidad Nacional de Costa Rica",
     "https://www.revistas.una.ac.cr/index.php/EDUCARE", "Scopus / WoS / SciELO / Redalyc"),
    ("Actualidades Investigativas en Educación", "Costa Rica", "Universidad de Costa Rica",
     "", "Scopus / SciELO / Redalyc"),
    ("Innovaciones Educativas", "Costa Rica", "Universidad Estatal a Distancia",
     "", "SciELO / DOAJ / Latindex"),
    ("Revista de Ciencias Sociales (UCR)", "Costa Rica", "Universidad de Costa Rica",
     "", "Redalyc / SciELO / ERIH PLUS / Latindex"),
    ("Reflexiones", "Costa Rica", "Universidad de Costa Rica", "", "Redalyc / SciELO / DOAJ"),
    ("Anuario de Estudios Centroamericanos", "Costa Rica", "Universidad de Costa Rica",
     "", "Scopus / SciELO / DOAJ"),

    # ─────────────────────────── PANAMÁ ───────────────────────────
    ("Acción y Reflexión Educativa", "Panamá", "Universidad de Panamá",
     "https://revistas.up.ac.pa/index.php/accion_reflexion_educativa",
     "Latindex Catálogo / DOAJ"),
    ("Revista Orbis Cognita", "Panamá", "Universidad de Panamá",
     "https://revistas.up.ac.pa/index.php/orbis_cognita", "Latindex Catálogo / DOAJ"),
    ("Societas. Revista de Ciencias Sociales y Humanísticas", "Panamá", "Universidad de Panamá",
     "https://revistas.up.ac.pa/index.php/societas", "Latindex Catálogo / DOAJ"),
    ("Cátedra", "Panamá", "Universidad de Panamá",
     "https://revistas.up.ac.pa/index.php/catedra", "Latindex Catálogo / DOAJ"),

    # ─────────────────────────── EL SALVADOR ───────────────────────────
    ("Revista Entorno", "El Salvador", "Universidad Tecnológica de El Salvador",
     "", "CamJOL / Latindex"),
    ("ECA. Estudios Centroamericanos", "El Salvador",
     "Universidad Centroamericana José Simeón Cañas", "", "Redalyc / CLACSO / Latindex"),
    ("Realidad. Revista de Ciencias Sociales y Humanidades", "El Salvador",
     "Universidad Centroamericana José Simeón Cañas",
     "https://camjol.info/index.php/REALIDAD", "CamJOL / CLACSO / Latindex"),

    # ─────────────────────────── GUATEMALA ───────────────────────────
    ("Revista Docencia Universitaria", "Guatemala", "Universidad de San Carlos de Guatemala",
     "", "Latindex"),
    ("Revista Académica CUNZAC", "Guatemala", "Centro Universitario de Zacapa, USAC",
     "", "Latindex Catálogo / DOAJ"),
    ("Revista Ciencias Sociales y Humanidades", "Guatemala",
     "Dirección General de Investigación, USAC", "", "Latindex / Dialnet"),

    # ─────────────────────────── HONDURAS ───────────────────────────
    ("Paradigma. Revista de Investigación Educativa", "Honduras",
     "Universidad Nacional Autónoma de Honduras", "", "CamJOL / Latindex / DOAJ"),
    ("Revista de Ciencias Sociales (UNAH)", "Honduras",
     "Universidad Nacional Autónoma de Honduras", "", "CamJOL / Latindex / DOAJ / CLACSO"),
    ("Economía y Administración", "Honduras", "Universidad Nacional Autónoma de Honduras",
     "", "Latindex Catálogo / DOAJ"),

    # ─────────────────────────── NICARAGUA ───────────────────────────
    ("Revista Torreón Universitario", "Nicaragua", "UNAN-Managua",
     "", "SciELO Nicaragua / DOAJ / Latindex"),
    ("Revista Científica de FAREM-Estelí", "Nicaragua", "UNAN-Managua",
     "", "CamJOL / DOAJ / Latindex"),
    ("Ciencia e Interculturalidad", "Nicaragua", "URACCAN",
     "", "SciELO Nicaragua / CamJOL / Latindex"),

    # ─────────────────────────── MÉXICO ───────────────────────────
    ("Revista Mexicana de Investigación Educativa", "México", "COMIE",
     "", "Scopus / WoS / SciELO México / Redalyc"),
    ("Perfiles Educativos", "México", "IISUE, UNAM",
     "https://perfileseducativos.unam.mx/iisue_pe/index.php/perfiles",
     "Scopus / SciELO México / Redalyc"),
    ("Revista Latinoamericana de Estudios Educativos (México)", "México",
     "Universidad Iberoamericana", "https://rlee.ibero.mx/", "Scopus / SciELO México / Redalyc"),
    ("Revista de la Educación Superior", "México", "ANUIES",
     "https://resu.anuies.mx/ojs/index.php/resu", "Scopus / WoS / SciELO México"),
    ("Sinéctica", "México", "ITESO", "https://sinectica.iteso.mx/",
     "Scopus / SciELO México / Redalyc"),
    ("Revista Electrónica de Investigación Educativa", "México",
     "Universidad Autónoma de Baja California", "https://redie.uabc.mx/redie",
     "Scopus / WoS / SciELO México"),
    ("Estudios Sociológicos", "México", "El Colegio de México",
     "", "Scopus / WoS / SciELO México / Redalyc"),
    ("Revista Mexicana de Sociología", "México", "IIS, UNAM",
     "", "Scopus / WoS / SciELO México"),
    ("Desacatos", "México", "CIESAS", "", "Scopus / SciELO México / Redalyc / WoS"),
    ("Foro Internacional", "México", "El Colegio de México",
     "", "Scopus / WoS / SciELO México"),
    ("Revista Mexicana de Ciencias Políticas y Sociales", "México", "FCPyS, UNAM",
     "", "Scopus / SciELO México / Redalyc"),
    ("Alteridades", "México", "UAM-Iztapalapa",
     "https://alteridades.izt.uam.mx/index.php/Alte", "Scopus / SciELO México / Redalyc"),
    ("Acta Sociológica", "México", "FCPyS, UNAM", "", "SciELO México / Latindex / Redalyc"),
    ("Espiral. Estudios sobre Estado y Sociedad", "México", "Universidad de Guadalajara",
     "https://espiral.cucsh.udg.mx/index.php/EEES", "Scopus / SciELO México / Redalyc"),
    ("Signos Históricos", "México", "UAM-Iztapalapa",
     "https://signoshistoricos.izt.uam.mx/index.php/historicos",
     "Scopus / SciELO México / Redalyc"),
    ("Iztapalapa. Revista de Ciencias Sociales y Humanidades", "México", "UAM-Iztapalapa",
     "", "Scopus / SciELO México / Redalyc"),
    ("Frontera Norte", "México", "El Colegio de la Frontera Norte",
     "https://fronteranorte.colef.mx/", "Scopus / SciELO México / WoS"),
    ("Región y Sociedad", "México", "El Colegio de Sonora",
     "", "Scopus / SciELO México / WoS"),
    ("Andamios. Revista de Investigación Social", "México",
     "Universidad Autónoma de la Ciudad de México",
     "https://andamios.uacm.edu.mx/index.php/andamios", "Scopus / SciELO México / Redalyc"),
    ("Cultura y Representaciones Sociales", "México", "IIS, UNAM",
     "https://www.culturayrs.unam.mx/index.php/CRS", "SciELO México / Redalyc / Latindex"),
    ("Revista Mexicana de Historia de la Educación", "México", "SOMEHIDE",
     "", "Latindex Catálogo / DOAJ / ERIH PLUS"),
    ("RIDE. Revista Iberoamericana para la Investigación y el Desarrollo Educativo",
     "México", "CENID", "https://www.ride.org.mx/index.php/RIDE",
     "SciELO México / WoS / Latindex"),
    ("Diálogos sobre Educación", "México", "Universidad de Guadalajara",
     "https://dialogossobreeducacion.cucsh.udg.mx/index.php/DSE",
     "SciELO México / Redalyc / Latindex"),
    ("CPU-e. Revista de Investigación Educativa", "México", "Universidad Veracruzana",
     "https://cpue.uv.mx/index.php/cpue", "SciELO México / Redalyc / Latindex"),
    ("Diánoia", "México", "Instituto de Investigaciones Filosóficas, UNAM",
     "", "Scopus / WoS / SciELO México"),
    ("Polis (México)", "México", "UAM-Iztapalapa", "", "SciELO México / Redalyc"),
    ("Relaciones. Estudios de Historia y Sociedad", "México", "El Colegio de Michoacán",
     "https://revistarelaciones.colmich.edu.mx/index.php/relaciones",
     "Scopus / WoS / SciELO México / Redalyc"),
    ("Trace. Travaux et Recherches dans les Amériques du Centre", "México", "CEMCA",
     "", "Scopus / SciELO México / Redalyc"),
    ("Nueva Antropología", "México", "Asociación Nueva Antropología / INAH / UNAM",
     "", "SciELO México / Redalyc / Latindex"),
    ("Tla-melaua. Revista de Ciencias Sociales", "México",
     "Benemérita Universidad Autónoma de Puebla", "", "SciELO México / Redalyc / Latindex"),
    ("Culturales", "México", "Universidad Autónoma de Baja California",
     "https://culturales.uabc.mx/index.php/Culturales", "Scopus / SciELO México / Redalyc"),
    ("Estudios sobre las Culturas Contemporáneas", "México", "Universidad de Colima",
     "", "Redalyc / Latindex / DOAJ"),
    ("Convergencia. Revista de Ciencias Sociales", "México",
     "Universidad Autónoma del Estado de México",
     "", "Scopus / WoS / SciELO México / Redalyc"),

    # ─────────────────────────── BOLIVIA ───────────────────────────
    ("Temas Sociales", "Bolivia", "IDIS, Universidad Mayor de San Andrés",
     "", "SciELO Bolivia / Redalyc / Latindex"),
    ("Tinkazos", "Bolivia", "PIEB / CIDES-UMSA", "", "SciELO Bolivia / CLACSO"),

    # ─────────────────────── CARIBE HISPANO ───────────────────────
    ("Pedagogía (Puerto Rico)", "Puerto Rico", "Universidad de Puerto Rico, Río Piedras",
     "", "Latindex Catálogo / DOAJ"),
    ("Revista Caribeña de Investigación Educativa", "República Dominicana", "ISFODOSU",
     "https://revistas.isfodosu.edu.do/index.php/recie", "SciELO / DOAJ / Latindex"),
    ("Revista de Ciencias Sociales (UPR)", "Puerto Rico",
     "Centro de Investigaciones Sociales, UPR", "", "Latindex / CLACSO / DOAJ"),

    # ────────────────── REVISTAS PUENTE / REGIONALES ──────────────────
    ("Revista Iberoamericana de Educación", "Iberoamérica (OEI)",
     "Organización de Estados Iberoamericanos", "https://rieoei.org/RIE",
     "Scopus / WoS / SciELO / DOAJ"),
    ("Revista Latinoamericana de Estudios Educativos (Colombia)", "Colombia",
     "Universidad de Caldas", "", "Redalyc / SciELO / Latindex"),
    ("Crítica y Resistencias", "Argentina/regional", "Red interuniversitaria CLACSO",
     "https://www.criticayresistencias.com.ar/", "Latindex Catálogo / DOAJ / CLACSO"),

    # ─────────────────────────── PORTUGAL ───────────────────────────
    ("Revista Portuguesa de Educação", "Portugal",
     "Instituto de Educação, Universidade do Minho",
     "https://revistas.rcaap.pt/rpe/", "Scopus / WoS / SciELO Portugal / DOAJ"),
    ("Revista Portuguesa de Pedagogia", "Portugal",
     "Universidade de Coimbra", "https://impactum-journals.uc.pt/rppedagogia",
     "ERIH PLUS / DOAJ / Latindex / RCAAP"),
    ("Revista Lusófona de Educação", "Portugal",
     "CeED, Universidade Lusófona de Humanidades e Tecnologias",
     "", "Scopus / WoS / SciELO Portugal"),
    ("Indagatio Didactica", "Portugal", "CIDTFF, Universidade de Aveiro",
     "https://proa.ua.pt/index.php/id", "DOAJ / ERIH PLUS / Latindex"),
    ("Sisyphus. Journal of Education", "Portugal",
     "Instituto de Educação, Universidade de Lisboa", "", "Scopus / WoS / DOAJ"),
    ("Investigar em Educação", "Portugal",
     "Sociedade Portuguesa de Ciências da Educação", "", "ERIH PLUS / Latindex"),
    ("Análise Social", "Portugal",
     "Instituto de Ciências Sociais, Universidade de Lisboa",
     "https://analisesocial.ics.ulisboa.pt/", "Scopus / WoS (SSCI) / SciELO Portugal"),
    ("Sociologia, Problemas e Práticas", "Portugal", "CIES-Iscte, ISCTE-IUL",
     "https://journals.openedition.org/spp/", "Scopus / WoS / SciELO Portugal"),
    ("Configurações", "Portugal", "CICS.NOVA.UMinho, Universidade do Minho",
     "https://journals.openedition.org/configuracoes/",
     "ERIH PLUS / DOAJ / Latindex / OpenEdition"),
    ("Forum Sociológico", "Portugal", "CICS.NOVA, NOVA FCSH",
     "", "ERIH PLUS / DOAJ / OpenEdition"),

    # ─────────────────────────── ESPAÑA ───────────────────────────
    ("Profesorado. Revista de Currículum y Formación del Profesorado", "España",
     "Universidad de Granada", "https://revistaseug.ugr.es/index.php/profesorado",
     "Scopus / WoS (ESCI) / FECYT"),
    ("Bordón. Revista de Pedagogía", "España", "Sociedad Española de Pedagogía",
     "https://recyt.fecyt.es/index.php/BORDON", "Scopus / WoS (ESCI) / FECYT"),
    ("Revista Española de Pedagogía", "España",
     "Universidad Internacional de La Rioja", "https://revistadepedagogia.org/",
     "Scopus / WoS (SSCI)"),
    ("Revista de Educación (España)", "España",
     "Ministerio de Educación, Formación Profesional y Deportes",
     "https://www.educacionyfp.gob.es/revista-de-educacion/inicio.html",
     "Scopus / WoS (SSCI)"),
    ("Organización y Gestión Educativa", "España",
     "Fórum Europeo de Administradores de la Educación",
     "https://www.oge.net/", "Latindex"),
    ("Educatio Siglo XXI", "España", "Universidad de Murcia",
     "https://revistas.um.es/educatio", "Scopus / WoS (ESCI) / FECYT"),
    ("Teoría de la Educación. Revista Interuniversitaria", "España",
     "Universidad de Salamanca", "", "Scopus / WoS (ESCI) / FECYT"),
    ("Educación XX1", "España", "UNED",
     "https://revistas.uned.es/index.php/educacionXX1",
     "Scopus / WoS (SSCI) / FECYT"),
    ("REICE. Revista Iberoamericana sobre Calidad, Eficacia y Cambio en Educación",
     "España", "Universidad Autónoma de Madrid / Red RINACE",
     "https://revistas.uam.es/reice", "Scopus / WoS (ESCI) / FECYT"),
    ("Revista Complutense de Educación", "España",
     "Universidad Complutense de Madrid", "https://revistas.ucm.es/index.php/RCED",
     "Scopus / WoS (ESCI) / FECYT"),
    ("Pedagogía Social. Revista Interuniversitaria", "España",
     "Sociedad Iberoamericana de Pedagogía Social",
     "https://recyt.fecyt.es/index.php/PSRI/", "Scopus / WoS (ESCI) / FECYT"),
    ("Historia y Memoria de la Educación", "España",
     "Sociedad Española de Historia de la Educación / UNED",
     "", "Scopus / WoS (ESCI) / FECYT"),
    ("RASE. Revista de Sociología de la Educación", "España",
     "Asociación Española de Sociología de la Educación / Universitat de València",
     "", "Scopus / WoS (ESCI) / FECYT"),
    ("Revista Española de Investigaciones Sociológicas", "España",
     "Centro de Investigaciones Sociológicas", "", "Scopus / WoS (SSCI)"),
    ("Papers. Revista de Sociologia", "España",
     "Universitat Autònoma de Barcelona", "https://papers.uab.cat/",
     "Scopus / WoS (ESCI) / FECYT"),
    ("Revista Española de Ciencia Política", "España",
     "Asociación Española de Ciencia Política y de la Administración",
     "https://recp.es/", "Scopus / WoS (ESCI) / FECYT"),
    ("Isegoría", "España", "Instituto de Filosofía, CSIC",
     "https://isegoria.revistas.csic.es/", "Scopus / WoS (AHCI) / FECYT"),
    ("Revista Internacional de Sociología", "España", "IESA-CSIC",
     "https://revintsociologia.revistas.csic.es/", "Scopus / WoS (SSCI)"),
    ("Empiria. Revista de Metodología de Ciencias Sociales", "España", "UNED",
     "https://revistas.uned.es/index.php/empiria",
     "Scopus / WoS (SSCI) / Redalyc / FECYT"),

    # ───────────── METODOLOGÍA DE LA INVESTIGACIÓN SOCIAL ─────────────
    ("Revista Latinoamericana de Metodología de las Ciencias Sociales", "Argentina",
     "CIMeCS, Universidad Nacional de La Plata",
     "https://www.relmecs.fahce.unlp.edu.ar/",
     "SciELO Argentina / DOAJ / Latindex / Dialnet"),
    ("Revista Latinoamericana de Metodología de la Investigación Social",
     "Argentina/regional", "CIES / Red Latinoamericana de Metodología",
     "http://www.relmis.com.ar/", "Latindex Catálogo / DOAJ / CLACSO / ERIH PLUS"),

    # ───────────────────── incorporaciones posteriores ─────────────────────
    ("Políticas Educativas (PolEd)", "Brasil",
     "Asociación de Universidades Grupo Montevideo / UFRGS",
     "https://seer.ufrgs.br/index.php/Poled", "Latindex / RCAAP / portal SEER"),
    ("Revista Internacional de Educación para la Justicia Social", "España",
     "Universidad Autónoma de Madrid / Red RINACE",
     "https://revistas.uam.es/riejs", "Scopus / DOAJ / Latindex / ERIH PLUS"),
    ("Cuadernos de la Facultad de Humanidades y Ciencias Sociales", "Argentina",
     "Universidad Nacional de Jujuy",
     "https://revistas.fhycs.unju.edu.ar/revistacuadernos/index.php/cuadernos",
     "Latindex / DOAJ / Núcleo Básico"),

    # ── incorporadas a partir de convocatorias relevadas (agosto 2026) ──
    # El país es el declarado por la fuente; la resolución contra DOAJ y
    # Scopus queda registrada en el campo `resolucion` de cada revista, para
    # poder verificar que se emparejó con la publicación correcta.
    ("Revista Significantes", "Argentina", "", "", "no declarada"),
    ("RICAP. Revista Integradora de la Comunidad Académica en Psicología",
     "México", "", "", "no declarada"),
    ("Argonautas. Revista de Educación y Ciencias Sociales", "Argentina",
     "Universidad Nacional de San Luis", "", "no declarada"),
    ("Historia y Región", "Argentina", "", "", "no declarada"),
    ("Dearq", "Colombia", "Universidad de los Andes", "", "Scopus / DOAJ"),
    ("Disertaciones", "Colombia", "Universidad del Rosario", "", "Scopus / DOAJ"),
    ("Dixit", "Uruguay", "Universidad Católica del Uruguay", "", "SciELO / DOAJ"),
    ("Encuentros Uruguayos", "Uruguay", "Universidad de la República",
     "", "Latindex / DOAJ"),
    ("Acervo", "Brasil", "Arquivo Nacional", "", "SciELO / DOAJ"),
    ("Desafíos: Economía y Empresa", "Perú", "", "", "no declarada"),
    ("Revista Perspectivas (UNIMINUTO)", "Colombia",
     "Corporación Universitaria Minuto de Dios", "", "no declarada"),
    ("Cotopaxi Tech", "Ecuador", "", "", "no declarada"),
    ("Millcayac. Revista Digital de Ciencias Sociales", "Argentina",
     "Universidad Nacional de Cuyo", "", "Latindex / DOAJ"),
    ("Cuadernos del Sur. Letras", "Argentina", "Universidad Nacional del Sur",
     "", "Latindex / Núcleo Básico"),
    ("Liberabit. Revista Peruana de Psicología", "Perú",
     "Universidad de San Martín de Porres", "", "Scopus / SciELO / DOAJ"),
    ("Jangwa Pana", "Colombia", "Universidad del Magdalena", "", "DOAJ / Latindex"),
    ("Cadernos de Filosofia Alemã: Crítica e Modernidade", "Brasil",
     "Universidade de São Paulo", "", "DOAJ / Latindex"),
    ("[re]Design", "Argentina", "", "", "no declarada"),
    ("Claves. Revista de Historia", "Uruguay", "Universidad de la República",
     "", "SciELO / DOAJ / Latindex"),
    ("Contribuciones desde Coatepec", "México",
     "Universidad Autónoma del Estado de México", "", "Redalyc / Latindex"),
]

